# Generated by Django 4.2.4 on 2025-05-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AidResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
